---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    controller:
      nodeSelector:
        kubernetes.io/os: linux
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        externalTrafficPolicy: Local
        type: LoadBalancer
