apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demoapp
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: demoapp
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    controller:
      nodeSelector:
        kubernetes.io/os: linux
        workload_type: application_linux
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        externalTrafficPolicy: Local
        type: LoadBalancer