apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: appgitopsvotecertificate
  namespace: demoapp
spec:
  secretName: appsecret
  commonName: app.gitopsvote.com
  dnsNames:
  - app.gitopsvote.com
  issuerRef:
    name: appissuer
    kind: appgitopsvoteissuer